config/routes.rb
PhotoHackDay::Application.routes.draw do

  root :to => 'experiments#index'
  match "/photos/download-popular" => "photos#download_popular"
  match "/photos/ajax" => "photos#ajax"
  match "/photos/offset/(:offset)" => "photos#index"

  resources :experiments

  resources :photos

end

app/models/photo.rb
class Photo < ActiveRecord::Base
	attr_protected
  # attr_accessible :title, :body

  def self.numeric? v
  	!!(v =~ /^[-+]?[0-9]*\.?[0-9]+$/)
  end

  def self.fraction? v
  	!!(v =~ /^[0-9]*\.?[0-9]+((\/[0-9]*\.?)|([0-9]*))[0-9]+$/)
  end

  def self.f_number v
  	r = /^([fF]\/?|)([0-9]*\.?[0-9]+$)/
  	result = r.match(v)
  	if result.nil?
  		false
  	else
  		result.captures[1]
  	end
  end

  def self.create_from_500px_full photo
  	photo.delete(:user)
  	Photo.create photo do |p|
  		p.id = photo[:id]
  	end
  end



  def self.floatify hash, key
  	hash[key] = hash[key].to_f
  	hash
  end

  def self.fractionify hash, key
  	if hash[key].include?('/')
  		hash[key] = hash[key].split('/')[0].to_f / hash[key].split('/')[1].to_f
  	else
  		hash[key] = hash[key].to_f
  	end
  	return hash
  end

  def self.f_numberify hash, key
  	hash[key] = f_number(hash[key])
  	hash
  end

  def self.filter_focal_length photos
  	photos.reject{|p| !numeric?(p.focal_length)}.map do |p|
  		floatify p, :focal_length
  	end
  end

  def self.filter_iso isos
  	isos.reject{|p| !numeric?(p.iso)}.map do |p|
  		floatify p, :iso
  	end
  end

  def self.filter_shutter_speed sss
  	raw_speeds = sss.reject{|p| !fraction?(p.shutter_speed)}
  	floats = raw_speeds.map do |p|
  		fractionify p, :shutter_speed
  	end
  end

  def self.filter_aperture as
  	raw = as.map do |p|
  		f_numberify p, :aperture
  	end
  	raw.reject{|p| p.aperture==false}.map do |p|
  		floatify p, :aperture
  	end
  end

  def self.ten_times_filter arr #removes items from the end of the array until the last one is less than 2 times the 2nd last
  	while arr[-1] > 10*arr[-2]
  		arr.pop
  	end
  	arr
  end



  def self.get_distinct_focal_lengths
  	raw = filter_focal_length (self.order.select("DISTINCT(focal_length)"))
  	ten_times_filter raw.map(&:focal_length).sort
  end

  def self.get_distinct_isos
  	raw = filter_iso (Photo.order.select("DISTINCT(iso)"))
  	ten_times_filter raw.map(&:iso).sort
  end

  def self.get_distinct_shutter_speeds
  	raw = filter_shutter_speed (Photo.select("DISTINCT(shutter_speed)"))
  	ten_times_filter raw.map(&:shutter_speed).sort
  end

  def self.get_distinct_apertures
  	raw = filter_aperture (Photo.select("DISTINCT(aperture)"))
  	ten_times_filter raw.map(&:aperture).uniq.sort
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	protect_from_forgery

  	require 'rubygems'
	# require 'oauth'
	require 'rest-client'
	require 'multi_json'
	require 'PP'

	CONSUMER_KEY = 'pGVlonYGLD206DIJEi5nwADa1ScsE6XTW5sZ7UME'
	CONSUMER_SECRET = 'lkBQONDoYtjfk0W1W9iyoII4NoQ7vm9GFR3IBXlV'
	USERNAME = ''
	PASSWORD = ''

	BASE_URL = 'https://api.500px.com/v1/'

	before_filter :set_cache_buster

	def set_cache_buster
		response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
	    response.headers["Pragma"] = "no-cache"
	    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
	end

  	def get_from_500px resource=nil, opts=nil
		query_url = BASE_URL + ""
		unless resource.nil?
			resource.each do |r|
				query_url.concat("#{r}/")
			end
		end
		query_url.concat "?consumer_key=#{CONSUMER_KEY}"

		unless opts.nil?
			opts.each do |opt, value|
				query_url.concat("&#{opt}=#{value}")
			end
		end

		raw_data = RestClient.get query_url

		# puts query_url
		puts raw_data.code

		json = MultiJson.decode(raw_data)

		recursive_symbolize_keys!(json)
		json
	end

	def recursive_symbolize_keys! hash
	    hash.symbolize_keys!
	    hash.values.select do |v|
	    	recursive_symbolize_keys!(v) if v.is_a? Hash
	    	v.each { |item| recursive_symbolize_keys!(item) } if (v.is_a? Array and v.first.is_a? Hash)
	    end
	  end

  	def get_photo_details photo_ids
  		photos = []
  		photo_ids.each do |id|
  			photos << (get_from_500px ["photos", id])[:photo]
  		end
  		photos
  	end
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
	
	def index
		# popular_photos = get_from_500px ["photos"], :feature => "popular"
		# @data = get_photo_details(popular_photos[:photos][0..2].map {|p| p[:id]})

		@range = {}
		@range[:focal_length] = Photo.get_distinct_focal_lengths
		@range[:iso] = Photo.get_distinct_isos
		@range[:shutter_speed] = Photo.get_distinct_shutter_speeds
		@range[:aperture] = Photo.get_distinct_apertures
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	def index
		params[:offset] ||= 0
		@photos = Photo.limit(50).offset(params[:offset])
	end

	def show
		@photo = Photo.find(params[:id].to_i)
	end

	def ajax
		arr = Photo.order("focal_length DESC")
		arr = Photo.filter_focal_length(arr)
		arr = Photo.filter_iso(arr)
		arr = Photo.filter_shutter_speed(arr)
		arr = Photo.filter_aperture(arr)

		result = arr.sort_by { |item| diff_score(params, item) }.first

		# oops, forgot to save user records
		result["user"] = (get_from_500px ["users", result["user_id"]])[:user]
		# grab fraction form of shutter speed, if available
		result["shutter_speed"] = (get_photo_details [result["id"]])[0][:shutter_speed]

		render :json => result
	end

	def diff_score params, item
		score = 0
		# unless params[:aperture].to_f == 0 and item[:aperture] == 0
		# 	score += (params[:aperture].to_f-item[:aperture]).abs / [item[:aperture], params[:aperture].to_f].max
		# end
		# unless params[:focal_length].to_f == 0 and item[:focal_length] == 0
		# 	score += (params[:focal_length].to_f-item[:focal_length]).abs / [item[:focal_length], params[:focal_length].to_f].max
		# end
		# unless params[:iso].to_f == 0 and item[:iso] == 0
		# 	score += (params[:iso].to_f-item[:iso]).abs / [item[:iso], params[:iso].to_f].max
		# end
		# unless params[:shutter_speed].to_f == 0 and item[:shutter_speed] == 0
		# 	score += (params[:shutter_speed].to_f-item[:shutter_speed]).abs / [item[:shutter_speed], params[:shutter_speed].to_f].max
		# end
		score += (params[:aperture].to_f - item[:aperture]).abs / 14
		score += (params[:iso].to_f - item[:iso]).abs / 500
		score += (params[:focal_length].to_f - item[:focal_length]).abs / 210
		score += (params[:shutter_speed].to_f - item[:shutter_speed]).abs / 0.05
	end

	def download_popular
		Photo.destroy_all

		(1..250).each do |i|
			puts "----------------------------------------"
			puts "ON PAGE #{i}"
			puts "----------------------------------------"

			popular_photos = get_from_500px ["photos"], :feature => "popular", :page => i
			photos = get_photo_details(popular_photos[:photos].map{ |p| p[:id] })
			photos.each do |photo|
				begin
					Photo.create_from_500px_full photo
				rescue Exception => e
					puts ""
					puts "ERRORRRRR!!!!! #{e}"
					puts ""
				end
			end
		end

		redirect_to photos_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
	#actually I don't need this method...
	def pretty_dump obj
		pretty = ""
		if obj.is_a Array
			pretty.concat "<ul>"
			obj.each_index do |i|
				pretty.concat "<li>[#{i}] #{pretty_dump obj[i]}<\li>"
			end
			pretty.concat "</ul>"
		elsif obj.is_a Hash
			pretty.concat "<ul>"
			obj.each do |k, v|
				pretty.concat "<li>#{k} => #{pretty_dump obj[i]}<\li>"
			end
			pretty.concat "</ul>"
		else
			pretty.concat obj
		end
		pretty
	end
end

app/views/experiments/index.html.haml
- content_for :head do
	%script{:type => "text/javascript", :src => "https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"}
	%script{:type => "text/javascript", :src => "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/jquery-ui.min.js"}
	%script{:type => "text/javascript", :src => "/assets/sliders.js"}
	%link{:rel => "stylesheet", :type => "text/css", :href => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.21/themes/base/jquery-ui.css"}
	%link{:rel => "stylesheet", :type => "text/css", :href => "/assets/experiments.css"}

#featureImage
	%a{:href => "#", :target => "_blank"}
		%img

#sliders
	-#camera
	-#lens
	#focalLength
		%p{:value => "Focal Length: "} Focal Length: 0 mm
		%div{:name => "focal_length", :data_min => @range[:focal_length].first, :data_max => "210"}
		-#@range[:focal_length].last}
	#iso
		%p{:value => "ISO: "} ISO: 0
		%div{:name => "iso", :data_min => @range[:iso].first, :data_max => "500"}
		-#@range[:iso].last}
	#shutterSpeed
		%p{:value => "Shutter Speed: "} Shutter Speed: 0 sec
		%div{:name => "shutter_speed", :data_min => "0", :data_max => "0.05"}
			-#@range[:shutter_speed].last}
	#aperture
		%p{:value => "Aperture: f/"} Aperture: f/0
		%div{:name => "aperture", :data_min => @range[:aperture].first, :data_max => "14"}
		-#@range[:aperture].last}
	%br

#stats
	%h2
		%a{:href => "#", :target => "_blank"}
	%p
	%ul

-##range
-#	-@range.each do |k, v|
-#		%div
-#			%h3= k
-#			%ul
-#				-v.each do |f|
-#					%li= f

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
	%head
		%title PhotoHackDay
		= yield :head
		- #stylesheet_link_tag    "application", :media => "all"
		- #javascript_include_tag "application"
		- #csrf_meta_tags
	%body
		= yield

app/views/photos/index.html.haml
%ul
	- @photos.each do |photo|
		%li= link_to photo[:name], photo_path(photo[:id])

app/views/photos/show.html.haml
%ul
	- @photo.attributes.each do |k, v|
		- if k == "image_url"
			%li
				= "#{k} => "
				= link_to v, v
		- else
			%li= "#{k} => #{v}"